# Generated by Django 2.1 on 2019-09-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0002_auto_20190918_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, default='fotos/profile.png', null=True, upload_to='fotos/', verbose_name='Cargar imagen'),
        ),
    ]
