# Generated by Django 2.1 on 2019-12-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0006_auto_20191212_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='prestadorServicio',
        ),
    ]
