# Generated by Django 2.1 on 2019-12-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0007_remove_servicios_prestadorservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='prestador',
            field=models.TextField(default='null', max_length=45),
        ),
    ]
