# Generated by Django 2.1 on 2019-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewApp', '0008_servicios_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='prestador',
            field=models.TextField(max_length=45),
        ),
    ]
